[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xfel"
version = "2024"
dynamic = ["scripts"]

[tool.setuptools.dynamic]
entry-points = { file = ["entry_points.ini"] }
